version: '2'
services:
    boncmd2-app:
        image: boncmd2
        external_links:
            - boncmd2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/boncmd2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boncmd2-mysql:
        extends:
            file: mysql.yml
            service: boncmd2-mysql
